## Modellgüte (Visualisierung)

# Plot 1: Lineare Regression
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.3, color="blue", label="Vorhersagen")
plt.plot([0, 45], [0, 45], color="red", linestyle="--", label="Ideal")
plt.xlim(0, 45)
plt.ylim(5, 20)
plt.xlabel("Tatsächlicher PM2.5-Wert")
plt.ylabel("Vorhergesagter PM2.5-Wert")
plt.title("Modellgüte: Lineare Regression")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# Plot 2: Random Forest
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred_rf, alpha=0.3, color="green", label="Vorhersagen")
plt.plot([0, 45], [0, 45], color="red", linestyle="--", label="Ideal")
plt.xlim(0, 45)
plt.ylim(5, 20)
plt.xlabel("Tatsächlicher PM2.5-Wert")
plt.ylabel("Vorhergesagter PM2.5-Wert")
plt.title("Modellgüte: Random Forest")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()
